[package]
name = "interactsh-rs-client"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = false

[lib]
name = "interactsh_rs_client"
path = "src/lib.rs"

[dependencies]
