name: CI Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE*'
  workflow_dispatch:

jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install the nightly Rust toolchain"
        run: rustup toolchain install nightly -c rustfmt

      - name: "Check formatting"
        run: cargo +nightly fmt --check

  dependancy_check:
    strategy:
      fail-fast: false
      matrix:
        features:
          - "rustcrypto,rustls-tls,async-compat"
          - "openssl,native-tls,log-stream"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install cargo-deny tool"
        run: cargo install cargo-deny

      - name: "Check dependancies"
        run: cargo deny --no-default-features --features ${{ matrix.features }} check
          
  call_test_suite:
    uses: ./.github/workflows/test_suite.yml
    secrets: inherit
        
  call_os_compat:
    needs: call_test_suite
    uses: ./.github/workflows/os_compat.yml
