name: OS Compatibility Tests
on:
  workflow_dispatch:
  workflow_call:

jobs:
  linux_and_mac:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crypto:
          - "rustcrypto rustls-tls"
          - "openssl native-tls"
          - "openssl-vendored native-tls-vendored"
        compat:
          - ""
          - " async-compat"
        log_stream:
          - ""
          - " log-stream"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
          
      - name: "Run HTTP test"
        run: cargo test --no-default-features --features "${{ matrix.crypto }}${{ matrix.compat }}${{ matrix.log_stream }}" --no-fail-fast http_logs_from_pub
        
  win-msvc:
    strategy:
      fail-fast: false
      matrix:
        crypto:
          - "rustcrypto rustls-tls"
          - "openssl native-tls"
          - "openssl-vendored native-tls-vendored"
        compat:
          - ""
          - " async-compat"
        log_stream:
          - ""
          - " log-stream"
    runs-on: windows-latest
    steps:
      - name: "Install OpenSSL"
        if: ${{ matrix.crypto }} != "rustcrypto rustls-tls"
        run: |
          vcpkg install openssl:x64-windows-static
          vcpkg integrate install

      - name: "Checkout"
        uses: actions/checkout@v3
          
      - name: "Run HTTP test"
        run: cargo test --no-default-features --features "${{ matrix.crypto }}${{ matrix.compat }}${{ matrix.log_stream }}" --no-fail-fast http_logs_from_pub
        env:
          OPENSSL_DIR: 'C:\vcpkg\installed\x64-windows-static'

  win_gnu:
    strategy:
      fail-fast: false
      matrix:
        crypto:
          - "rustcrypto rustls-tls"
          - "openssl native-tls"
          - "openssl-vendored native-tls-vendored"
        compat:
          - ""
          - " async-compat"
        log_stream:
          - ""
          - " log-stream"
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2 environment and MinGW+Rust toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel
            openssl-devel
            pkg-config
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-rust
        
      - name: "Checkout"
        uses: actions/checkout@v3
          
      - name: "Run HTTP test"
        run: cargo test --no-default-features --features "${{ matrix.crypto }}${{ matrix.compat }}${{ matrix.log_stream }}" --no-fail-fast http_logs_from_pub --target x86_64-pc-windows-gnu